
title: [The title of your site]
description: [A short description of your site's purpose]

theme: minima

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/jekyll/jekyll" }
    - { platform: twitter, user_url: "https://twitter.com/jekyllrb" }

